Algoritmo "manzano_L04k"
// Disciplina   : [Logica de Programacao com JavaScript]
// Professor   : Jailson
// Descrição   :
// Autor(a)    : Ana Luiza Jesus Ferreira
// Data atual  : 07/04/2024
Var
// Seção de Declarações das variáveis 
   valor: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   escreval("Digite um valor")
   leia(valor)
   se valor <3 entao
   escreval("Valor informado", valor)
   fimse

Fimalgoritmo